### ISSUE TITLE
feature suggestion: support release containers

### ISSUE THREAD

**Issue by jwnx** [kpcyrd/repro-env#27]
We could extend `repro-env` to create reproducible release containers by having a separate config for release image and its dependencies. For example:

```toml
system = "debian"

[build]
image = "debian:bookworm"
dependencies = ["gcc", "libc6-dev"]

[release]
image = "gcr.io/distroless/base-nossl-debian12:nonroot"
dependencies = ["gcc"]
```

I can implement this, if approved.
