### ISSUE TITLE
feature suggestion: lock package version

### ISSUE THREAD

**Issue by jwnx** [kpcyrd/repro-env#28]
We could allow to specify package versions in order to have granular control over the build environment (not sure if doable in alpine). For example:

```toml
# repro-env.toml
[container]
image = "debian:bookworm"

[packages]
system = "debian"
dependencies = ["gcc=1.0.0", "libc6-dev=1.0.0"]
```
